<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS8981;CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\third_party\CodeWalker\CodeWalker.Core\CodeWalker.Core.csproj" />
  </ItemGroup>
</Project>
