#!/usr/bin/env python3
"""Generate gta/src/natives_gen.h from alloc8or's nativedb (third_party/natives.json).

Every native becomes `inline R NAMESPACE::NAME(args)` calling invoke<R>(hash, args...). ScriptHookV translates
these (original PC) hashes for the running game build.
"""
import json
import keyword
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "third_party" / "natives.json"
OUT = ROOT / "gta" / "src" / "natives_gen.h"

HANDLE_TYPES = {"Any", "Ped", "Vehicle", "Entity", "Player", "Cam", "Object", "Blip", "Pickup", "Interior",
                "ScrHandle", "FireId"}
CPP_KEYWORDS = {"default", "class", "new", "this", "template", "operator", "delete", "register", "char", "int",
                "float", "bool", "struct", "union", "switch", "case", "public", "private", "protected", "friend",
                "virtual", "unsigned", "signed", "short", "long", "double", "auto", "const", "volatile", "goto",
                "inline", "namespace", "using", "typename", "explicit", "export", "extern", "static", "return",
                "void", "enum", "mutable", "do", "for", "if", "else", "while", "break", "continue", "try", "catch",
                "throw", "true", "false", "sizeof", "typedef", "near", "far", "interface", "small", "max", "min"}


def ctype(t: str) -> str:
    base = t.replace("const ", "").strip()
    if base.endswith("*"):
        inner = base[:-1].strip()
        if inner in HANDLE_TYPES:
            return "int*"
        if inner == "Hash":
            return "Hash*"
        return t  # Vector3*, BOOL*, int*, float*, char*
    if base in HANDLE_TYPES:
        return "int"
    return t


def ident(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name[0].isdigit():
        name = "_" + name
    return name


def main():
    data = json.loads(SRC.read_text())
    out = ["// GENERATED by tools/gen_natives.py from alloc8or's nativedb. Do not edit.", "#pragma once",
           '#include "shv.h"', ""]
    for ns, funcs in data.items():
        out.append(f"namespace {ns} {{")
        seen = set()
        for h, f in funcs.items():
            name = ident(f["name"])
            if name in seen:
                continue
            seen.add(name)
            params = []
            names = []
            used = set()
            for i, p in enumerate(f["params"]):
                pn = ident(p["name"]) or f"p{i}"
                if pn.lower() in CPP_KEYWORDS or keyword.iskeyword(pn) or pn in used:
                    pn = f"{pn}_{i}"
                used.add(pn)
                params.append(f"{ctype(p['type'])} {pn}")
                names.append(pn)
            ret = ctype(f["return_type"])
            args = "".join(", " + n for n in names)
            body = f"return invoke<{ret}>({h}ULL{args});"
            out.append(f"\tinline {ret} {name}({', '.join(params)}) {{ {body} }}")
        out.append("}")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({sum(len(v) for v in data.values())} natives)")


if __name__ == "__main__":
    sys.exit(main())
